---
apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
  labels:
    role: app
    env: demo
    app: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-proxy-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
        - name: app
          image: bdossantos/fluxcd-basic-demo:1.0.1 # {"$imagepolicy": "flux-system:app"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: nginx-conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: demo
data:
  nginx.conf: |-
    server {
      listen 80;
      server_name localhost;

      location / {
        proxy_pass http://127.0.0.1:5000/;
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: demo
  labels:
    app: flux
    env: demo
    role: app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    role: app
  type: NodePort
status:
  loadBalancer: {}
